inherit_gem:
  rubocop-infinum: rubocop.yml

require: rubocop-infinum

AllCops:
  TargetRubyVersion: 3.0.1

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false