steps:
  download_remote_db_dump:
    s3_credentials:
      access_key_id: 'access_key_id'
      access_key: 'access_key'
      region: 'region'
      bucket: 'bucket_name'
    source_file_path: 'attachments/staging.sql'
    destination_file_path: './tmp/downloaded_db_dump.sql'
  create_local_db_backup:
    destination_file_path: './tmp/development_backup.sql'
  reset_local_db_schema:
  import_remote_db_to_local_db:
    remote_db_dump_file_path: './tmp/staging.sql'
  run_migrations_on_local_db:
  delete_remote_db_dump:
    remote_db_dump_file_path: './tmp/staging.sql'
  execute_custom_command:
    command: 'some command'
